# Generated by Django 4.2.4 on 2023-09-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='comment',
            new_name='coment',
        ),
    ]
